[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Chen Ze", email = "chenze_ustc@mail.ustc.edu.cn"}]
dynamic = ["version", "description"]
